// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `bridge`, `event_to_dto`, `host_status_to_dto`, `likes_progress_to_dto`, `progress_to_dto`, `track_to_dto`, `verdict_str`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Bridge`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Поднять ядро. Идемпотентно. Зовётся один раз после `RustLib.init()`.
/// [`dpi_bypass`] — включить пробив DPI как fallback (TLS-фрагментация).
Future<void> initRuntime(
        {required String dataDir,
        required String cacheDir,
        required bool dpiBypass}) =>
    RustLib.instance.api.crateApiInitRuntime(
        dataDir: dataDir, cacheDir: cacheDir, dpiBypass: dpiBypass);

Future<List<TrackDto>> search(
        {required String query, required int limit, required int offset}) =>
    RustLib.instance.api
        .crateApiSearch(query: query, limit: limit, offset: offset);

Future<TrackDto?> resolveTrack({required String urn}) =>
    RustLib.instance.api.crateApiResolveTrack(urn: urn);

Future<void> playTrack({required String urn}) =>
    RustLib.instance.api.crateApiPlayTrack(urn: urn);

Future<void> pause() => RustLib.instance.api.crateApiPause();

Future<void> resume() => RustLib.instance.api.crateApiResume();

Future<void> stop() => RustLib.instance.api.crateApiStop();

Future<void> seek({required double positionSecs}) =>
    RustLib.instance.api.crateApiSeek(positionSecs: positionSecs);

Future<void> setVolume({required double volume}) =>
    RustLib.instance.api.crateApiSetVolume(volume: volume);

Future<void> setSpeed({required double speed}) =>
    RustLib.instance.api.crateApiSetSpeed(speed: speed);

Future<void> setEq({required bool enabled, required List<double> gains}) =>
    RustLib.instance.api.crateApiSetEq(enabled: enabled, gains: gains);

/// Hover-превью трека: дожать кэш и проиграть сэмпл на отдельном плеере. Окно/
/// гейт/дебаунс — на стороне UI (как легаси `audioPreview`).
Future<void> audioPreviewPlay({required String urn, required double volume}) =>
    RustLib.instance.api.crateApiAudioPreviewPlay(urn: urn, volume: volume);

/// Снять hover-превью с фейдом (мс). `preview_stop` спавнит фейд-задачу — входим
/// в рантайм (FRB зовёт вне него).
Future<void> audioPreviewStop({required BigInt fadeMs}) =>
    RustLib.instance.api.crateApiAudioPreviewStop(fadeMs: fadeMs);

Future<void> setAbLoop({double? a, double? b}) =>
    RustLib.instance.api.crateApiSetAbLoop(a: a, b: b);

/// Доступные выходные аудиоустройства (для пикера в настройках).
Future<List<AudioDeviceDto>> audioOutputDevices() =>
    RustLib.instance.api.crateApiAudioOutputDevices();

/// Переключить аудиовыход (`None` — системный по умолчанию). Текущий трек
/// переезжает на новое устройство с сохранением позиции.
Future<void> setAudioOutput({String? name}) =>
    RustLib.instance.api.crateApiSetAudioOutput(name: name);

Future<double> positionSecs() => RustLib.instance.api.crateApiPositionSecs();

Future<bool> isPlaying() => RustLib.instance.api.crateApiIsPlaying();

Future<void> setSession({String? token}) =>
    RustLib.instance.api.crateApiSetSession(token: token);

/// Позиция воспроизведения (latest-wins).
Stream<double> positionStream() =>
    RustLib.instance.api.crateApiPositionStream();

/// Критические события (Ended/TrackChanged).
Stream<PlaybackEventDto> playbackEvents() =>
    RustLib.instance.api.crateApiPlaybackEvents();

/// Статус бэкенд-хостов для UI: вердикты main/star ("up"|"down"|"unknown") +
/// premium. Отдаёт текущее значение сразу, далее — при каждом изменении. На этом
/// фронт строит модалки failover (резерв STAR / купи STAR / всё лежит).
Stream<HostStatusDto> hostStatusStream() =>
    RustLib.instance.api.crateApiHostStatusStream();

/// Внеочередная перепроверка хостов (кнопка «Проверить снова» в модалке failover).
Future<void> hostRecheck() => RustLib.instance.api.crateApiHostRecheck();

/// Прогресс скачки текущего трека (доля 0..1) для индикатора в NowBar.
Stream<DownloadProgressDto> downloadProgress() =>
    RustLib.instance.api.crateApiDownloadProgress();

/// Прогресс bulk-кэша лайков ({done,failed,total,finished}) для настроек.
Stream<LikesProgressDto> likesProgress() =>
    RustLib.instance.api.crateApiLikesProgress();

/// Поток лог-полос спектра (`Vec<f32>`, 64 полосы, ~30 Гц) для визуализатора.
/// FFT считается в ядре только пока есть подписчик — иначе CPU-idle.
Stream<Float32List> audioSpectrum() =>
    RustLib.instance.api.crateApiAudioSpectrum();

/// Выходное аудиоустройство для пикера в настройках. `name` — идентификатор для
/// переключения, `description` — человекочитаемое имя в UI.
class AudioDeviceDto {
  final String name;
  final String description;
  final bool isDefault;

  const AudioDeviceDto({
    required this.name,
    required this.description,
    required this.isDefault,
  });

  @override
  int get hashCode => name.hashCode ^ description.hashCode ^ isDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioDeviceDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          isDefault == other.isDefault;
}

@freezed
sealed class BridgeError with _$BridgeError implements FrbException {
  const BridgeError._();

  const factory BridgeError.notInitialized() = BridgeError_NotInitialized;
  const factory BridgeError.init(
    String field0,
  ) = BridgeError_Init;
  const factory BridgeError.core(
    String field0,
  ) = BridgeError_Core;
}

/// Прогресс скачки трека для индикатора в NowBar: `urn` — какой трек, `fraction`
/// — доля 0..1 (только фаза скачивания; транскод процента не даёт).
class DownloadProgressDto {
  final String urn;
  final double fraction;

  const DownloadProgressDto({
    required this.urn,
    required this.fraction,
  });

  @override
  int get hashCode => urn.hashCode ^ fraction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadProgressDto &&
          runtimeType == other.runtimeType &&
          urn == other.urn &&
          fraction == other.fraction;
}

/// Статус бэкенд-хостов для UI-модалок failover.
class HostStatusDto {
  /// Вердикт основного хоста: `"up"` | `"down"` | `"unknown"`.
  final String main;

  /// Вердикт STAR-резерва.
  final String star;

  /// Активна ли подписка (открывает STAR).
  final bool premium;

  const HostStatusDto({
    required this.main,
    required this.star,
    required this.premium,
  });

  @override
  int get hashCode => main.hashCode ^ star.hashCode ^ premium.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostStatusDto &&
          runtimeType == other.runtimeType &&
          main == other.main &&
          star == other.star &&
          premium == other.premium;
}

/// Прогресс bulk-кэша лайков для индикатора в настройках.
class LikesProgressDto {
  final int done;
  final int failed;
  final int total;
  final bool finished;

  const LikesProgressDto({
    required this.done,
    required this.failed,
    required this.total,
    required this.finished,
  });

  @override
  int get hashCode =>
      done.hashCode ^ failed.hashCode ^ total.hashCode ^ finished.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LikesProgressDto &&
          runtimeType == other.runtimeType &&
          done == other.done &&
          failed == other.failed &&
          total == other.total &&
          finished == other.finished;
}

@freezed
sealed class PlaybackEventDto with _$PlaybackEventDto {
  const PlaybackEventDto._();

  const factory PlaybackEventDto.ended() = PlaybackEventDto_Ended;
  const factory PlaybackEventDto.trackChanged({
    required String urn,
  }) = PlaybackEventDto_TrackChanged;
}

class TrackAlbumDto {
  final String id;
  final String title;
  final String? coverUrl;
  final int? year;

  const TrackAlbumDto({
    required this.id,
    required this.title,
    this.coverUrl,
    this.year,
  });

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ coverUrl.hashCode ^ year.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackAlbumDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          coverUrl == other.coverUrl &&
          year == other.year;
}

class TrackDto {
  final String urn;
  final String title;
  final String artistName;
  final String artistId;
  final String? artistAvatarUrl;
  final BigInt durationMs;
  final String? artworkUrl;
  final String? waveformUrl;
  final String? genre;
  final BigInt? playCount;
  final BigInt? likesCount;
  final BigInt? repostsCount;
  final String? permalinkUrl;
  final String? createdAt;
  final int? releaseYear;
  final String? uploaderId;
  final String? uploaderUsername;
  final String? uploaderPermalinkUrl;
  final String? uploaderAvatarUrl;
  final bool uploaderVerified;
  final String? storageState;
  final String? storageQuality;
  final String? indexState;
  final String? enrichState;
  final bool? userFavorite;
  final bool isCover;
  final String? description;
  final List<String> tags;
  final String? isrc;
  final String? language;
  final TrackAlbumDto? album;
  final List<TrackParticipantDto> participants;

  const TrackDto({
    required this.urn,
    required this.title,
    required this.artistName,
    required this.artistId,
    this.artistAvatarUrl,
    required this.durationMs,
    this.artworkUrl,
    this.waveformUrl,
    this.genre,
    this.playCount,
    this.likesCount,
    this.repostsCount,
    this.permalinkUrl,
    this.createdAt,
    this.releaseYear,
    this.uploaderId,
    this.uploaderUsername,
    this.uploaderPermalinkUrl,
    this.uploaderAvatarUrl,
    required this.uploaderVerified,
    this.storageState,
    this.storageQuality,
    this.indexState,
    this.enrichState,
    this.userFavorite,
    required this.isCover,
    this.description,
    required this.tags,
    this.isrc,
    this.language,
    this.album,
    required this.participants,
  });

  @override
  int get hashCode =>
      urn.hashCode ^
      title.hashCode ^
      artistName.hashCode ^
      artistId.hashCode ^
      artistAvatarUrl.hashCode ^
      durationMs.hashCode ^
      artworkUrl.hashCode ^
      waveformUrl.hashCode ^
      genre.hashCode ^
      playCount.hashCode ^
      likesCount.hashCode ^
      repostsCount.hashCode ^
      permalinkUrl.hashCode ^
      createdAt.hashCode ^
      releaseYear.hashCode ^
      uploaderId.hashCode ^
      uploaderUsername.hashCode ^
      uploaderPermalinkUrl.hashCode ^
      uploaderAvatarUrl.hashCode ^
      uploaderVerified.hashCode ^
      storageState.hashCode ^
      storageQuality.hashCode ^
      indexState.hashCode ^
      enrichState.hashCode ^
      userFavorite.hashCode ^
      isCover.hashCode ^
      description.hashCode ^
      tags.hashCode ^
      isrc.hashCode ^
      language.hashCode ^
      album.hashCode ^
      participants.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackDto &&
          runtimeType == other.runtimeType &&
          urn == other.urn &&
          title == other.title &&
          artistName == other.artistName &&
          artistId == other.artistId &&
          artistAvatarUrl == other.artistAvatarUrl &&
          durationMs == other.durationMs &&
          artworkUrl == other.artworkUrl &&
          waveformUrl == other.waveformUrl &&
          genre == other.genre &&
          playCount == other.playCount &&
          likesCount == other.likesCount &&
          repostsCount == other.repostsCount &&
          permalinkUrl == other.permalinkUrl &&
          createdAt == other.createdAt &&
          releaseYear == other.releaseYear &&
          uploaderId == other.uploaderId &&
          uploaderUsername == other.uploaderUsername &&
          uploaderPermalinkUrl == other.uploaderPermalinkUrl &&
          uploaderAvatarUrl == other.uploaderAvatarUrl &&
          uploaderVerified == other.uploaderVerified &&
          storageState == other.storageState &&
          storageQuality == other.storageQuality &&
          indexState == other.indexState &&
          enrichState == other.enrichState &&
          userFavorite == other.userFavorite &&
          isCover == other.isCover &&
          description == other.description &&
          tags == other.tags &&
          isrc == other.isrc &&
          language == other.language &&
          album == other.album &&
          participants == other.participants;
}

class TrackParticipantDto {
  final String? id;
  final String name;
  final String? role;

  const TrackParticipantDto({
    this.id,
    required this.name,
    this.role,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ role.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackParticipantDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          role == other.role;
}
