// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'api.dart';
import 'dto.dart';
import 'dto_social.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<VibePageDto> searchVibe({required String query, required int limit}) =>
    RustLib.instance.api.crateDataSocialSearchVibe(query: query, limit: limit);

/// Живой поиск треков прямо в SoundCloud (источник «SC»).
Future<List<TrackDto>> searchScTracks(
        {required String query, required int limit}) =>
    RustLib.instance.api
        .crateDataSocialSearchScTracks(query: query, limit: limit);

Future<LyricHitPageDto> searchLyrics(
        {required String query, required int limit}) =>
    RustLib.instance.api
        .crateDataSocialSearchLyrics(query: query, limit: limit);

Future<TrackPageDto> artistCovers(
        {required String id, required int limit, required int offset}) =>
    RustLib.instance.api
        .crateDataSocialArtistCovers(id: id, limit: limit, offset: offset);

Future<ArtistStarDto> artistStar({required String id}) =>
    RustLib.instance.api.crateDataSocialArtistStar(id: id);

Future<List<ClusterDto>> recommendationsSimilar(
        {required String trackId, required int limit}) =>
    RustLib.instance.api
        .crateDataSocialRecommendationsSimilar(trackId: trackId, limit: limit);

Future<List<ClusterDto>> recommendationsArtist(
        {required String artistId, required int limit}) =>
    RustLib.instance.api
        .crateDataSocialRecommendationsArtist(artistId: artistId, limit: limit);

Future<UserDto?> user({required String urn}) =>
    RustLib.instance.api.crateDataSocialUser(urn: urn);

Future<TrackPageDto> userTracks(
        {required String urn, required int limit, required int offset}) =>
    RustLib.instance.api
        .crateDataSocialUserTracks(urn: urn, limit: limit, offset: offset);

Future<PlaylistSummaryPageDto> userPlaylists(
        {required String urn, required int limit, required int offset}) =>
    RustLib.instance.api
        .crateDataSocialUserPlaylists(urn: urn, limit: limit, offset: offset);

Future<TrackPageDto> userLikedTracks(
        {required String urn, required int limit, required int offset}) =>
    RustLib.instance.api
        .crateDataSocialUserLikedTracks(urn: urn, limit: limit, offset: offset);

Future<UserPageDto> userFollowers(
        {required String urn, required int limit, required int offset}) =>
    RustLib.instance.api
        .crateDataSocialUserFollowers(urn: urn, limit: limit, offset: offset);

Future<UserPageDto> userFollowings(
        {required String urn, required int limit, required int offset}) =>
    RustLib.instance.api
        .crateDataSocialUserFollowings(urn: urn, limit: limit, offset: offset);

Future<List<WebProfileDto>> userWebProfiles({required String urn}) =>
    RustLib.instance.api.crateDataSocialUserWebProfiles(urn: urn);

Future<bool> userSubscription({required String urn}) =>
    RustLib.instance.api.crateDataSocialUserSubscription(urn: urn);

Future<UserPageDto> meFollowings({required int limit, required int offset}) =>
    RustLib.instance.api
        .crateDataSocialMeFollowings(limit: limit, offset: offset);

Future<TrackPageDto> meFollowingsTracks(
        {required int limit, required int offset}) =>
    RustLib.instance.api
        .crateDataSocialMeFollowingsTracks(limit: limit, offset: offset);

Future<AuraDto> userAura({required String urn}) =>
    RustLib.instance.api.crateDataSocialUserAura(urn: urn);

Future<AuraDto> putAura({required String auraId, String? customHex}) =>
    RustLib.instance.api
        .crateDataSocialPutAura(auraId: auraId, customHex: customHex);

Future<UserPageDto> trackFavoriters(
        {required String urn, required int limit}) =>
    RustLib.instance.api.crateDataSocialTrackFavoriters(urn: urn, limit: limit);

/// Комментарии трека (постранично).
Future<CommentPageDto> trackComments(
        {required String urn, required int limit, required int offset}) =>
    RustLib.instance.api
        .crateDataSocialTrackComments(urn: urn, limit: limit, offset: offset);

/// Оставить комментарий (`timestampMs` — таймкод в треке, `null` — без привязки).
Future<CommentDto> postComment(
        {required String urn,
        required String body,
        PlatformInt64? timestampMs}) =>
    RustLib.instance.api.crateDataSocialPostComment(
        urn: urn, body: body, timestampMs: timestampMs);

Future<UserPageDto> trackReposters({required String urn, required int limit}) =>
    RustLib.instance.api.crateDataSocialTrackReposters(urn: urn, limit: limit);

Future<TrackDto?> resolveUrl({required String url}) =>
    RustLib.instance.api.crateDataSocialResolveUrl(url: url);

Future<Float32List> trackWaveform({required String waveformUrl}) =>
    RustLib.instance.api.crateDataSocialTrackWaveform(waveformUrl: waveformUrl);

Future<void> likeTrack({required String trackUrn}) =>
    RustLib.instance.api.crateDataSocialLikeTrack(trackUrn: trackUrn);

Future<void> unlikeTrack({required String trackUrn}) =>
    RustLib.instance.api.crateDataSocialUnlikeTrack(trackUrn: trackUrn);

Future<void> likePlaylist({required String playlistUrn}) =>
    RustLib.instance.api.crateDataSocialLikePlaylist(playlistUrn: playlistUrn);

Future<void> unlikePlaylist({required String playlistUrn}) =>
    RustLib.instance.api
        .crateDataSocialUnlikePlaylist(playlistUrn: playlistUrn);

Future<void> followUser({required String userUrn}) =>
    RustLib.instance.api.crateDataSocialFollowUser(userUrn: userUrn);

Future<void> unfollowUser({required String userUrn}) =>
    RustLib.instance.api.crateDataSocialUnfollowUser(userUrn: userUrn);

Future<void> dislikeTrack({required String scTrackId}) =>
    RustLib.instance.api.crateDataSocialDislikeTrack(scTrackId: scTrackId);

Future<void> undislikeTrack({required String scTrackId}) =>
    RustLib.instance.api.crateDataSocialUndislikeTrack(scTrackId: scTrackId);

Future<bool> dislikeStatus({required String scTrackId}) =>
    RustLib.instance.api.crateDataSocialDislikeStatus(scTrackId: scTrackId);

Future<List<String>> dislikeIds() =>
    RustLib.instance.api.crateDataSocialDislikeIds();

Future<void> clearHistory() =>
    RustLib.instance.api.crateDataSocialClearHistory();

Future<WallpaperPageDto> wallpaperSearch({required WallpaperQueryDto query}) =>
    RustLib.instance.api.crateDataSocialWallpaperSearch(query: query);

/// Скачать обоину по URL в локальное хранилище — абсолютный путь файла.
Future<String> wallpaperDownload({required String url}) =>
    RustLib.instance.api.crateDataSocialWallpaperDownload(url: url);

/// Импортировать локальный файл (file-picker) в хранилище обоев.
Future<String> wallpaperImport({required String srcPath}) =>
    RustLib.instance.api.crateDataSocialWallpaperImport(srcPath: srcPath);

/// Абсолютные пути всех сохранённых обоев.
Future<List<String>> wallpaperList() =>
    RustLib.instance.api.crateDataSocialWallpaperList();

/// Удалить обоину по абсолютному пути.
Future<void> wallpaperRemove({required String path}) =>
    RustLib.instance.api.crateDataSocialWallpaperRemove(path: path);

Future<List<TrackDto>> resolveTracks({required List<String> urns}) =>
    RustLib.instance.api.crateDataSocialResolveTracks(urns: urns);

Future<TrackPageDto> playlistAddTrack(
        {required String playlistUrn, required String trackUrn}) =>
    RustLib.instance.api.crateDataSocialPlaylistAddTrack(
        playlistUrn: playlistUrn, trackUrn: trackUrn);

Future<TrackPageDto> playlistRemoveTrack(
        {required String playlistUrn, required String trackUrn}) =>
    RustLib.instance.api.crateDataSocialPlaylistRemoveTrack(
        playlistUrn: playlistUrn, trackUrn: trackUrn);

Future<TrackPageDto> playlistReorder(
        {required String playlistUrn, required List<String> trackUrns}) =>
    RustLib.instance.api.crateDataSocialPlaylistReorder(
        playlistUrn: playlistUrn, trackUrns: trackUrns);

Future<PlaylistSummaryDto> createPlaylist(
        {required String title, required List<String> trackUrns}) =>
    RustLib.instance.api
        .crateDataSocialCreatePlaylist(title: title, trackUrns: trackUrns);

Future<void> deletePlaylist({required String playlistUrn}) =>
    RustLib.instance.api
        .crateDataSocialDeletePlaylist(playlistUrn: playlistUrn);

Future<List<CacheEntryDto>> cacheInventory() =>
    RustLib.instance.api.crateDataSocialCacheInventory();

Future<PlatformInt64> cacheTotalBytes() =>
    RustLib.instance.api.crateDataSocialCacheTotalBytes();

Future<bool> cacheIsCached({required String urn}) =>
    RustLib.instance.api.crateDataSocialCacheIsCached(urn: urn);

Future<void> cacheRemove({required String urn}) =>
    RustLib.instance.api.crateDataSocialCacheRemove(urn: urn);

Future<void> cacheEnsure({required String urn}) =>
    RustLib.instance.api.crateDataSocialCacheEnsure(urn: urn);

/// Экспорт трека в файл (легаси `save_track_to_path`): путь даёт платформа.
Future<void> trackExport({required String urn, required String destPath}) =>
    RustLib.instance.api
        .crateDataSocialTrackExport(urn: urn, destPath: destPath);

/// Опережающий прогрев трека в фоне (легаси `track_preload`) — кэш без игры.
/// `preload_track` делает `tokio::spawn`, поэтому входим в контекст рантайма
/// (FRB зовёт нас вне него) — иначе паника «no reactor running».
Future<void> trackPreload({required String urn}) =>
    RustLib.instance.api.crateDataSocialTrackPreload(urn: urn);

Future<PlatformInt64> cacheLikedBytes() =>
    RustLib.instance.api.crateDataSocialCacheLikedBytes();

Future<void> cacheClear() => RustLib.instance.api.crateDataSocialCacheClear();

Future<void> cacheClearLiked() =>
    RustLib.instance.api.crateDataSocialCacheClearLiked();

/// Применить лимит обычного аудиокэша (LRU-вытеснение). Зовётся после скачки.
Future<void> cacheEnforceLimit({required BigInt limitMb}) =>
    RustLib.instance.api.crateDataSocialCacheEnforceLimit(limitMb: limitMb);

Future<bool> cacheLikesRunning() =>
    RustLib.instance.api.crateDataSocialCacheLikesRunning();

Future<void> cancelCacheLikes() =>
    RustLib.instance.api.crateDataSocialCancelCacheLikes();

/// Запустить bulk-кэш лайков в защищённый кэш. Возвращается сразу — прогресс
/// идёт потоком [`crate::api::likes_progress`], завершение — событием `finished`.
Future<void> cacheLikes({required List<String> urns}) =>
    RustLib.instance.api.crateDataSocialCacheLikes(urns: urns);
