// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'api.dart';
import 'dto.dart';
import 'dto_social.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<ArtistCardPageDto> searchArtists(
        {required String query, required int limit, required int offset}) =>
    RustLib.instance.api
        .crateDataSearchArtists(query: query, limit: limit, offset: offset);

Future<AlbumCardPageDto> searchAlbums(
        {required String query, required int limit, required int offset}) =>
    RustLib.instance.api
        .crateDataSearchAlbums(query: query, limit: limit, offset: offset);

Future<PlaylistSummaryPageDto> searchPlaylists(
        {required String query, required int limit, required int offset}) =>
    RustLib.instance.api
        .crateDataSearchPlaylists(query: query, limit: limit, offset: offset);

Future<UserPageDto> searchUsers(
        {required String query, required int limit, required int offset}) =>
    RustLib.instance.api
        .crateDataSearchUsers(query: query, limit: limit, offset: offset);

Future<TrackPageDto> trackRelated({required String urn, required int limit}) =>
    RustLib.instance.api.crateDataTrackRelated(urn: urn, limit: limit);

Future<TrackStreamsDto> trackStreams({required String urn}) =>
    RustLib.instance.api.crateDataTrackStreams(urn: urn);

Future<List<ClusterDto>> homeRiver(
        {required int limit,
        required List<String> languages,
        required bool hideListened}) =>
    RustLib.instance.api.crateDataHomeRiver(
        limit: limit, languages: languages, hideListened: hideListened);

Future<WaveDto> wave(
        {required int limit,
        String? cursor,
        required List<String> languages,
        required bool hideListened}) =>
    RustLib.instance.api.crateDataWave(
        limit: limit,
        cursor: cursor,
        languages: languages,
        hideListened: hideListened);

Future<void> recommendationsFeedback(
        {required String clusterId, required String kind}) =>
    RustLib.instance.api
        .crateDataRecommendationsFeedback(clusterId: clusterId, kind: kind);

Future<String?> waveFeedback(
        {required String cursor,
        required int negatives,
        required int positives}) =>
    RustLib.instance.api.crateDataWaveFeedback(
        cursor: cursor, negatives: negatives, positives: positives);

Future<DiscoverSummaryDto> discoverSummary() =>
    RustLib.instance.api.crateDataDiscoverSummary();

Future<DiscoverArtistsPageDto> discoverArtists(
        {required int limit,
        String? cursor,
        String? sort,
        String? tag,
        String? q}) =>
    RustLib.instance.api.crateDataDiscoverArtists(
        limit: limit, cursor: cursor, sort: sort, tag: tag, q: q);

Future<DiscoverAlbumsPageDto> discoverAlbums(
        {required int limit,
        String? cursor,
        String? sort,
        String? kind,
        String? q}) =>
    RustLib.instance.api.crateDataDiscoverAlbums(
        limit: limit, cursor: cursor, sort: sort, kind: kind, q: q);

Future<List<AlbumYearBucketDto>> discoverAlbumsByYear(
        {required int years, required int perYear, String? kind}) =>
    RustLib.instance.api.crateDataDiscoverAlbumsByYear(
        years: years, perYear: perYear, kind: kind);

Future<String?> discoverRandom({String? kind}) =>
    RustLib.instance.api.crateDataDiscoverRandom(kind: kind);

Future<List<TagDto>> discoverTags() =>
    RustLib.instance.api.crateDataDiscoverTags();

Future<SpotlightFeedDto> discoverSpotlight({int? limit}) =>
    RustLib.instance.api.crateDataDiscoverSpotlight(limit: limit);

Future<ArtistDetailDto> artistDetail({required String id}) =>
    RustLib.instance.api.crateDataArtistDetail(id: id);

Future<TrackPageDto> artistTracks(
        {required String id,
        required String role,
        required int limit,
        required int offset}) =>
    RustLib.instance.api.crateDataArtistTracks(
        id: id, role: role, limit: limit, offset: offset);

Future<List<AlbumRefDto>> artistAlbums({required String id}) =>
    RustLib.instance.api.crateDataArtistAlbums(id: id);

Future<AlbumDetailDto> albumDetail({required String id}) =>
    RustLib.instance.api.crateDataAlbumDetail(id: id);

Future<PlaylistDetailDto> playlistDetail(
        {required String urn, required int limit, required int offset}) =>
    RustLib.instance.api
        .crateDataPlaylistDetail(urn: urn, limit: limit, offset: offset);

/// Реальные треки плейлиста (summary часто отдаёт `tracks:null`).
Future<TrackPageDto> playlistTracks(
        {required String urn, required int limit, required int offset}) =>
    RustLib.instance.api
        .crateDataPlaylistTracks(urn: urn, limit: limit, offset: offset);

Future<MeDto> me() => RustLib.instance.api.crateDataMe();

Future<bool> meSubscription() => RustLib.instance.api.crateDataMeSubscription();

Future<TrackPageDto> libraryLikesTracks(
        {required int limit, required int offset}) =>
    RustLib.instance.api
        .crateDataLibraryLikesTracks(limit: limit, offset: offset);

Future<PlaylistSummaryPageDto> libraryLikesPlaylists(
        {required int limit, required int offset}) =>
    RustLib.instance.api
        .crateDataLibraryLikesPlaylists(limit: limit, offset: offset);

Future<PlaylistSummaryPageDto> libraryPlaylists(
        {required int limit, required int offset}) =>
    RustLib.instance.api
        .crateDataLibraryPlaylists(limit: limit, offset: offset);

Future<HistoryPageDto> history({required int limit, required int offset}) =>
    RustLib.instance.api.crateDataHistory(limit: limit, offset: offset);

Future<FeaturedDto> featured() => RustLib.instance.api.crateDataFeatured();

Future<LyricsDto?> lyrics({required String scTrackId}) =>
    RustLib.instance.api.crateDataLyrics(scTrackId: scTrackId);

Future<AuthStatusDto> authStatus() =>
    RustLib.instance.api.crateDataAuthStatus();

Future<LoginStartDto> authStartLogin() =>
    RustLib.instance.api.crateDataAuthStartLogin();

Future<LoginStatusDto> authPollLogin({required String loginRequestId}) =>
    RustLib.instance.api.crateDataAuthPollLogin(loginRequestId: loginRequestId);

Future<void> authLogout() => RustLib.instance.api.crateDataAuthLogout();

Future<LinkCreateDto> authLinkCreate({required String mode}) =>
    RustLib.instance.api.crateDataAuthLinkCreate(mode: mode);

Future<LinkStatusDto> authLinkStatus({required String linkRequestId}) =>
    RustLib.instance.api.crateDataAuthLinkStatus(linkRequestId: linkRequestId);

Future<LinkClaimDto> authLinkClaim({required String payload}) =>
    RustLib.instance.api.crateDataAuthLinkClaim(payload: payload);
