// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'api.dart';
import 'dto_pay.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<PlanDto>> payPlans() => RustLib.instance.api.crateDataPayPayPlans();

Future<SubscriptionDto> paySubscription() =>
    RustLib.instance.api.crateDataPayPaySubscription();

Future<List<OrderDto>> payOrders() =>
    RustLib.instance.api.crateDataPayPayOrders();

Future<OrderDto?> payOrder({required String id}) =>
    RustLib.instance.api.crateDataPayPayOrder(id: id);

Future<CheckoutDto> payCheckout(
        {required String planId,
        required String provider,
        String? method,
        bool? recurring}) =>
    RustLib.instance.api.crateDataPayPayCheckout(
        planId: planId,
        provider: provider,
        method: method,
        recurring: recurring);

Future<RedeemDto> payRedeem({required String code}) =>
    RustLib.instance.api.crateDataPayPayRedeem(code: code);

Future<void> payCancel({required String source}) =>
    RustLib.instance.api.crateDataPayPayCancel(source: source);
