// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'api.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class AlbumArtistDto {
  final String id;
  final String name;
  final String? role;
  final String? avatarUrl;

  const AlbumArtistDto({
    required this.id,
    required this.name,
    this.role,
    this.avatarUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ role.hashCode ^ avatarUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumArtistDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          role == other.role &&
          avatarUrl == other.avatarUrl;
}

class AlbumCardDto {
  final String id;
  final String title;
  final int? releaseYear;
  final int? releaseMonth;
  final String? coverUrl;
  final double confidence;
  final int trackCount;
  final BigInt? totalDurationMs;
  final double popularity;
  final bool star;
  final AlbumArtistDto primaryArtist;

  const AlbumCardDto({
    required this.id,
    required this.title,
    this.releaseYear,
    this.releaseMonth,
    this.coverUrl,
    required this.confidence,
    required this.trackCount,
    this.totalDurationMs,
    required this.popularity,
    required this.star,
    required this.primaryArtist,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      releaseYear.hashCode ^
      releaseMonth.hashCode ^
      coverUrl.hashCode ^
      confidence.hashCode ^
      trackCount.hashCode ^
      totalDurationMs.hashCode ^
      popularity.hashCode ^
      star.hashCode ^
      primaryArtist.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumCardDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          releaseYear == other.releaseYear &&
          releaseMonth == other.releaseMonth &&
          coverUrl == other.coverUrl &&
          confidence == other.confidence &&
          trackCount == other.trackCount &&
          totalDurationMs == other.totalDurationMs &&
          popularity == other.popularity &&
          star == other.star &&
          primaryArtist == other.primaryArtist;
}

class AlbumCardPageDto {
  final List<AlbumCardDto> items;
  final int page;
  final int pageSize;
  final bool hasMore;

  const AlbumCardPageDto({
    required this.items,
    required this.page,
    required this.pageSize,
    required this.hasMore,
  });

  @override
  int get hashCode =>
      items.hashCode ^ page.hashCode ^ pageSize.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumCardPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          pageSize == other.pageSize &&
          hasMore == other.hasMore;
}

class AlbumDetailDto {
  final String id;
  final String title;
  final int? releaseYear;
  final String? coverUrl;
  final double confidence;
  final AlbumArtistDto primaryArtist;
  final List<AlbumArtistDto> artists;
  final List<TrackDto> tracks;

  const AlbumDetailDto({
    required this.id,
    required this.title,
    this.releaseYear,
    this.coverUrl,
    required this.confidence,
    required this.primaryArtist,
    required this.artists,
    required this.tracks,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      releaseYear.hashCode ^
      coverUrl.hashCode ^
      confidence.hashCode ^
      primaryArtist.hashCode ^
      artists.hashCode ^
      tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumDetailDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          releaseYear == other.releaseYear &&
          coverUrl == other.coverUrl &&
          confidence == other.confidence &&
          primaryArtist == other.primaryArtist &&
          artists == other.artists &&
          tracks == other.tracks;
}

class AlbumRefDto {
  final String id;
  final String title;
  final int? releaseYear;
  final String? role;

  const AlbumRefDto({
    required this.id,
    required this.title,
    this.releaseYear,
    this.role,
  });

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ releaseYear.hashCode ^ role.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumRefDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          releaseYear == other.releaseYear &&
          role == other.role;
}

class ArtistCardDto {
  final String id;
  final String name;
  final String? country;
  final String? avatarUrl;
  final double confidence;
  final bool star;
  final int trackCountPrimary;
  final int trackCountFeatured;
  final int albumCount;
  final BigInt monthlyListeners;
  final double trending;
  final double popularity;
  final List<String> tags;
  final String? auraId;
  final String? customHex;

  const ArtistCardDto({
    required this.id,
    required this.name,
    this.country,
    this.avatarUrl,
    required this.confidence,
    required this.star,
    required this.trackCountPrimary,
    required this.trackCountFeatured,
    required this.albumCount,
    required this.monthlyListeners,
    required this.trending,
    required this.popularity,
    required this.tags,
    this.auraId,
    this.customHex,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      country.hashCode ^
      avatarUrl.hashCode ^
      confidence.hashCode ^
      star.hashCode ^
      trackCountPrimary.hashCode ^
      trackCountFeatured.hashCode ^
      albumCount.hashCode ^
      monthlyListeners.hashCode ^
      trending.hashCode ^
      popularity.hashCode ^
      tags.hashCode ^
      auraId.hashCode ^
      customHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtistCardDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          country == other.country &&
          avatarUrl == other.avatarUrl &&
          confidence == other.confidence &&
          star == other.star &&
          trackCountPrimary == other.trackCountPrimary &&
          trackCountFeatured == other.trackCountFeatured &&
          albumCount == other.albumCount &&
          monthlyListeners == other.monthlyListeners &&
          trending == other.trending &&
          popularity == other.popularity &&
          tags == other.tags &&
          auraId == other.auraId &&
          customHex == other.customHex;
}

class ArtistCardPageDto {
  final List<ArtistCardDto> items;
  final int page;
  final int pageSize;
  final bool hasMore;

  const ArtistCardPageDto({
    required this.items,
    required this.page,
    required this.pageSize,
    required this.hasMore,
  });

  @override
  int get hashCode =>
      items.hashCode ^ page.hashCode ^ pageSize.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtistCardPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          pageSize == other.pageSize &&
          hasMore == other.hasMore;
}

class ArtistDetailDto {
  final String id;
  final String name;
  final String? country;
  final String? bio;
  final String? avatarUrl;
  final double confidence;
  final int trackCount;
  final int trackCountPrimary;
  final int trackCountFeatured;
  final int albumCount;
  final List<SocialDto> socials;
  final List<ScAccountDto> scAccounts;
  final List<RelatedArtistDto> relatedArtists;
  final List<TrackDto> popularTracks;

  const ArtistDetailDto({
    required this.id,
    required this.name,
    this.country,
    this.bio,
    this.avatarUrl,
    required this.confidence,
    required this.trackCount,
    required this.trackCountPrimary,
    required this.trackCountFeatured,
    required this.albumCount,
    required this.socials,
    required this.scAccounts,
    required this.relatedArtists,
    required this.popularTracks,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      country.hashCode ^
      bio.hashCode ^
      avatarUrl.hashCode ^
      confidence.hashCode ^
      trackCount.hashCode ^
      trackCountPrimary.hashCode ^
      trackCountFeatured.hashCode ^
      albumCount.hashCode ^
      socials.hashCode ^
      scAccounts.hashCode ^
      relatedArtists.hashCode ^
      popularTracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtistDetailDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          country == other.country &&
          bio == other.bio &&
          avatarUrl == other.avatarUrl &&
          confidence == other.confidence &&
          trackCount == other.trackCount &&
          trackCountPrimary == other.trackCountPrimary &&
          trackCountFeatured == other.trackCountFeatured &&
          albumCount == other.albumCount &&
          socials == other.socials &&
          scAccounts == other.scAccounts &&
          relatedArtists == other.relatedArtists &&
          popularTracks == other.popularTracks;
}

/// Состояние авторизации для гейта. `has_session` — локальный токен,
/// `authenticated` — подтверждение бэкендом.
class AuthStatusDto {
  final bool hasSession;
  final bool authenticated;
  final String? sessionId;
  final String? username;
  final String? tokenState;

  const AuthStatusDto({
    required this.hasSession,
    required this.authenticated,
    this.sessionId,
    this.username,
    this.tokenState,
  });

  @override
  int get hashCode =>
      hasSession.hashCode ^
      authenticated.hashCode ^
      sessionId.hashCode ^
      username.hashCode ^
      tokenState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthStatusDto &&
          runtimeType == other.runtimeType &&
          hasSession == other.hasSession &&
          authenticated == other.authenticated &&
          sessionId == other.sessionId &&
          username == other.username &&
          tokenState == other.tokenState;
}

class ClusterDto {
  final String id;
  final List<String> trackIds;
  final List<ClusterNeighborDto> neighbors;

  const ClusterDto({
    required this.id,
    required this.trackIds,
    required this.neighbors,
  });

  @override
  int get hashCode => id.hashCode ^ trackIds.hashCode ^ neighbors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClusterDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          trackIds == other.trackIds &&
          neighbors == other.neighbors;
}

class ClusterNeighborDto {
  final String artistId;
  final String artistName;
  final String? avatarUrl;
  final String trackId;

  const ClusterNeighborDto({
    required this.artistId,
    required this.artistName,
    this.avatarUrl,
    required this.trackId,
  });

  @override
  int get hashCode =>
      artistId.hashCode ^
      artistName.hashCode ^
      avatarUrl.hashCode ^
      trackId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClusterNeighborDto &&
          runtimeType == other.runtimeType &&
          artistId == other.artistId &&
          artistName == other.artistName &&
          avatarUrl == other.avatarUrl &&
          trackId == other.trackId;
}

/// Комментарий трека (автор уплощён внутрь). `timestamp_ms` — таймкод в треке.
class CommentDto {
  final PlatformInt64 id;
  final String body;
  final PlatformInt64? timestampMs;
  final String? createdAt;
  final String userUrn;
  final String username;
  final String? avatarUrl;
  final String? permalinkUrl;

  const CommentDto({
    required this.id,
    required this.body,
    this.timestampMs,
    this.createdAt,
    required this.userUrn,
    required this.username,
    this.avatarUrl,
    this.permalinkUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      body.hashCode ^
      timestampMs.hashCode ^
      createdAt.hashCode ^
      userUrn.hashCode ^
      username.hashCode ^
      avatarUrl.hashCode ^
      permalinkUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommentDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          body == other.body &&
          timestampMs == other.timestampMs &&
          createdAt == other.createdAt &&
          userUrn == other.userUrn &&
          username == other.username &&
          avatarUrl == other.avatarUrl &&
          permalinkUrl == other.permalinkUrl;
}

class CommentPageDto {
  final List<CommentDto> items;
  final int page;
  final int pageSize;
  final bool hasMore;

  const CommentPageDto({
    required this.items,
    required this.page,
    required this.pageSize,
    required this.hasMore,
  });

  @override
  int get hashCode =>
      items.hashCode ^ page.hashCode ^ pageSize.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommentPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          pageSize == other.pageSize &&
          hasMore == other.hasMore;
}

class DiscoverSummaryDto {
  final BigInt artistsCount;
  final BigInt albumsCount;
  final BigInt freshCount;
  final int freshWindowDays;

  const DiscoverSummaryDto({
    required this.artistsCount,
    required this.albumsCount,
    required this.freshCount,
    required this.freshWindowDays,
  });

  @override
  int get hashCode =>
      artistsCount.hashCode ^
      albumsCount.hashCode ^
      freshCount.hashCode ^
      freshWindowDays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoverSummaryDto &&
          runtimeType == other.runtimeType &&
          artistsCount == other.artistsCount &&
          albumsCount == other.albumsCount &&
          freshCount == other.freshCount &&
          freshWindowDays == other.freshWindowDays;
}

/// Редакционный пик: один из полей задан в зависимости от `kind`.
class FeaturedDto {
  final String kind;
  final TrackDto? track;
  final PlaylistSummaryDto? playlist;

  const FeaturedDto({
    required this.kind,
    this.track,
    this.playlist,
  });

  @override
  int get hashCode => kind.hashCode ^ track.hashCode ^ playlist.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeaturedDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          track == other.track &&
          playlist == other.playlist;
}

class HistoryEntryDto {
  final String id;
  final String scTrackId;
  final String title;
  final String artistName;
  final String? artistUrn;
  final String? artworkUrl;
  final BigInt durationMs;
  final String playedAt;

  const HistoryEntryDto({
    required this.id,
    required this.scTrackId,
    required this.title,
    required this.artistName,
    this.artistUrn,
    this.artworkUrl,
    required this.durationMs,
    required this.playedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      scTrackId.hashCode ^
      title.hashCode ^
      artistName.hashCode ^
      artistUrn.hashCode ^
      artworkUrl.hashCode ^
      durationMs.hashCode ^
      playedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryEntryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          scTrackId == other.scTrackId &&
          title == other.title &&
          artistName == other.artistName &&
          artistUrn == other.artistUrn &&
          artworkUrl == other.artworkUrl &&
          durationMs == other.durationMs &&
          playedAt == other.playedAt;
}

class HistoryPageDto {
  final List<HistoryEntryDto> items;
  final int total;

  const HistoryPageDto({
    required this.items,
    required this.total,
  });

  @override
  int get hashCode => items.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          total == other.total;
}

class LinkClaimDto {
  final String? sessionId;
  final String? mode;

  const LinkClaimDto({
    this.sessionId,
    this.mode,
  });

  @override
  int get hashCode => sessionId.hashCode ^ mode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkClaimDto &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          mode == other.mode;
}

/// QR-перенос сессии: создан линк. `payload` — строка для QR.
class LinkCreateDto {
  final String linkRequestId;
  final String claimToken;
  final String mode;
  final String payload;
  final String? expiresAt;

  const LinkCreateDto({
    required this.linkRequestId,
    required this.claimToken,
    required this.mode,
    required this.payload,
    this.expiresAt,
  });

  @override
  int get hashCode =>
      linkRequestId.hashCode ^
      claimToken.hashCode ^
      mode.hashCode ^
      payload.hashCode ^
      expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkCreateDto &&
          runtimeType == other.runtimeType &&
          linkRequestId == other.linkRequestId &&
          claimToken == other.claimToken &&
          mode == other.mode &&
          payload == other.payload &&
          expiresAt == other.expiresAt;
}

class LinkStatusDto {
  final String status;
  final String? mode;
  final String? sessionId;
  final String? error;

  const LinkStatusDto({
    required this.status,
    this.mode,
    this.sessionId,
    this.error,
  });

  @override
  int get hashCode =>
      status.hashCode ^ mode.hashCode ^ sessionId.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkStatusDto &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          mode == other.mode &&
          sessionId == other.sessionId &&
          error == other.error;
}

class LoginStartDto {
  final String url;
  final String loginRequestId;

  const LoginStartDto({
    required this.url,
    required this.loginRequestId,
  });

  @override
  int get hashCode => url.hashCode ^ loginRequestId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoginStartDto &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          loginRequestId == other.loginRequestId;
}

class LoginStatusDto {
  final String status;
  final String? step;
  final String? sessionId;
  final String? username;
  final String? error;
  final String? redirectUrl;

  const LoginStatusDto({
    required this.status,
    this.step,
    this.sessionId,
    this.username,
    this.error,
    this.redirectUrl,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      step.hashCode ^
      sessionId.hashCode ^
      username.hashCode ^
      error.hashCode ^
      redirectUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoginStatusDto &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          step == other.step &&
          sessionId == other.sessionId &&
          username == other.username &&
          error == other.error &&
          redirectUrl == other.redirectUrl;
}

class LyricLineDto {
  final BigInt? atMs;
  final String text;

  const LyricLineDto({
    this.atMs,
    required this.text,
  });

  @override
  int get hashCode => atMs.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricLineDto &&
          runtimeType == other.runtimeType &&
          atMs == other.atMs &&
          text == other.text;
}

class LyricsDto {
  final bool synced;
  final String? source;
  final List<LyricLineDto> lines;

  const LyricsDto({
    required this.synced,
    this.source,
    required this.lines,
  });

  @override
  int get hashCode => synced.hashCode ^ source.hashCode ^ lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricsDto &&
          runtimeType == other.runtimeType &&
          synced == other.synced &&
          source == other.source &&
          lines == other.lines;
}

class MeDto {
  final String urn;
  final String username;
  final String? permalink;
  final String? permalinkUrl;
  final String? avatarUrl;
  final String? plan;
  final bool premium;
  final BigInt? followersCount;
  final BigInt? followingsCount;
  final BigInt? publicFavoritesCount;
  final BigInt? privatePlaylistsCount;
  final BigInt? playlistCount;

  const MeDto({
    required this.urn,
    required this.username,
    this.permalink,
    this.permalinkUrl,
    this.avatarUrl,
    this.plan,
    required this.premium,
    this.followersCount,
    this.followingsCount,
    this.publicFavoritesCount,
    this.privatePlaylistsCount,
    this.playlistCount,
  });

  @override
  int get hashCode =>
      urn.hashCode ^
      username.hashCode ^
      permalink.hashCode ^
      permalinkUrl.hashCode ^
      avatarUrl.hashCode ^
      plan.hashCode ^
      premium.hashCode ^
      followersCount.hashCode ^
      followingsCount.hashCode ^
      publicFavoritesCount.hashCode ^
      privatePlaylistsCount.hashCode ^
      playlistCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeDto &&
          runtimeType == other.runtimeType &&
          urn == other.urn &&
          username == other.username &&
          permalink == other.permalink &&
          permalinkUrl == other.permalinkUrl &&
          avatarUrl == other.avatarUrl &&
          plan == other.plan &&
          premium == other.premium &&
          followersCount == other.followersCount &&
          followingsCount == other.followingsCount &&
          publicFavoritesCount == other.publicFavoritesCount &&
          privatePlaylistsCount == other.privatePlaylistsCount &&
          playlistCount == other.playlistCount;
}

class PlaylistDetailDto {
  final PlaylistSummaryDto summary;
  final List<TrackDto> tracks;

  const PlaylistDetailDto({
    required this.summary,
    required this.tracks,
  });

  @override
  int get hashCode => summary.hashCode ^ tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistDetailDto &&
          runtimeType == other.runtimeType &&
          summary == other.summary &&
          tracks == other.tracks;
}

class PlaylistSummaryDto {
  final String urn;
  final String title;
  final String? artworkUrl;
  final bool isAlbum;
  final int trackCount;
  final BigInt? durationMs;
  final BigInt? likesCount;
  final BigInt? repostsCount;
  final String? permalinkUrl;
  final String? createdAt;
  final int? releaseYear;
  final String? ownerId;
  final String? ownerUsername;
  final String? ownerAvatarUrl;
  final bool? userFavorite;
  final String? description;
  final String? lastModified;
  final String? kind;

  const PlaylistSummaryDto({
    required this.urn,
    required this.title,
    this.artworkUrl,
    required this.isAlbum,
    required this.trackCount,
    this.durationMs,
    this.likesCount,
    this.repostsCount,
    this.permalinkUrl,
    this.createdAt,
    this.releaseYear,
    this.ownerId,
    this.ownerUsername,
    this.ownerAvatarUrl,
    this.userFavorite,
    this.description,
    this.lastModified,
    this.kind,
  });

  @override
  int get hashCode =>
      urn.hashCode ^
      title.hashCode ^
      artworkUrl.hashCode ^
      isAlbum.hashCode ^
      trackCount.hashCode ^
      durationMs.hashCode ^
      likesCount.hashCode ^
      repostsCount.hashCode ^
      permalinkUrl.hashCode ^
      createdAt.hashCode ^
      releaseYear.hashCode ^
      ownerId.hashCode ^
      ownerUsername.hashCode ^
      ownerAvatarUrl.hashCode ^
      userFavorite.hashCode ^
      description.hashCode ^
      lastModified.hashCode ^
      kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistSummaryDto &&
          runtimeType == other.runtimeType &&
          urn == other.urn &&
          title == other.title &&
          artworkUrl == other.artworkUrl &&
          isAlbum == other.isAlbum &&
          trackCount == other.trackCount &&
          durationMs == other.durationMs &&
          likesCount == other.likesCount &&
          repostsCount == other.repostsCount &&
          permalinkUrl == other.permalinkUrl &&
          createdAt == other.createdAt &&
          releaseYear == other.releaseYear &&
          ownerId == other.ownerId &&
          ownerUsername == other.ownerUsername &&
          ownerAvatarUrl == other.ownerAvatarUrl &&
          userFavorite == other.userFavorite &&
          description == other.description &&
          lastModified == other.lastModified &&
          kind == other.kind;
}

class PlaylistSummaryPageDto {
  final List<PlaylistSummaryDto> items;
  final int page;
  final int pageSize;
  final bool hasMore;

  const PlaylistSummaryPageDto({
    required this.items,
    required this.page,
    required this.pageSize,
    required this.hasMore,
  });

  @override
  int get hashCode =>
      items.hashCode ^ page.hashCode ^ pageSize.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistSummaryPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          pageSize == other.pageSize &&
          hasMore == other.hasMore;
}

class RelatedArtistDto {
  final String id;
  final String name;
  final String? country;
  final String? avatarUrl;
  final double weight;

  const RelatedArtistDto({
    required this.id,
    required this.name,
    this.country,
    this.avatarUrl,
    required this.weight,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      country.hashCode ^
      avatarUrl.hashCode ^
      weight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelatedArtistDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          country == other.country &&
          avatarUrl == other.avatarUrl &&
          weight == other.weight;
}

class ScAccountDto {
  final String scUserId;
  final String? role;
  final String? source;
  final bool verified;

  const ScAccountDto({
    required this.scUserId,
    this.role,
    this.source,
    required this.verified,
  });

  @override
  int get hashCode =>
      scUserId.hashCode ^ role.hashCode ^ source.hashCode ^ verified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScAccountDto &&
          runtimeType == other.runtimeType &&
          scUserId == other.scUserId &&
          role == other.role &&
          source == other.source &&
          verified == other.verified;
}

class SocialDto {
  final String kind;
  final String url;
  final String? source;
  final bool verified;

  const SocialDto({
    required this.kind,
    required this.url,
    this.source,
    required this.verified,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ url.hashCode ^ source.hashCode ^ verified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SocialDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          url == other.url &&
          source == other.source &&
          verified == other.verified;
}

class TagDto {
  final String id;
  final String label;
  final BigInt count;

  const TagDto({
    required this.id,
    required this.label,
    required this.count,
  });

  @override
  int get hashCode => id.hashCode ^ label.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          count == other.count;
}

/// Страница списка треков для Dart.
class TrackPageDto {
  final List<TrackDto> items;
  final int page;
  final int pageSize;
  final bool hasMore;

  const TrackPageDto({
    required this.items,
    required this.page,
    required this.pageSize,
    required this.hasMore,
  });

  @override
  int get hashCode =>
      items.hashCode ^ page.hashCode ^ pageSize.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          pageSize == other.pageSize &&
          hasMore == other.hasMore;
}

class TrackStreamsDto {
  final String? hlsAac160Url;
  final String? hlsMp3128Url;
  final String? httpMp3128Url;
  final String? previewMp3128Url;

  const TrackStreamsDto({
    this.hlsAac160Url,
    this.hlsMp3128Url,
    this.httpMp3128Url,
    this.previewMp3128Url,
  });

  @override
  int get hashCode =>
      hlsAac160Url.hashCode ^
      hlsMp3128Url.hashCode ^
      httpMp3128Url.hashCode ^
      previewMp3128Url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackStreamsDto &&
          runtimeType == other.runtimeType &&
          hlsAac160Url == other.hlsAac160Url &&
          hlsMp3128Url == other.hlsMp3128Url &&
          httpMp3128Url == other.httpMp3128Url &&
          previewMp3128Url == other.previewMp3128Url;
}

class UserDto {
  final String urn;
  final String username;
  final String? permalink;
  final String? permalinkUrl;
  final String? avatarUrl;
  final String? fullName;
  final String? city;
  final String? countryCode;
  final String? description;
  final bool verified;
  final BigInt? followersCount;
  final BigInt? followingsCount;
  final BigInt? trackCount;
  final BigInt? playlistCount;
  final PlatformInt64? publicFavoritesCount;
  final String? plan;
  final String? createdAt;

  const UserDto({
    required this.urn,
    required this.username,
    this.permalink,
    this.permalinkUrl,
    this.avatarUrl,
    this.fullName,
    this.city,
    this.countryCode,
    this.description,
    required this.verified,
    this.followersCount,
    this.followingsCount,
    this.trackCount,
    this.playlistCount,
    this.publicFavoritesCount,
    this.plan,
    this.createdAt,
  });

  @override
  int get hashCode =>
      urn.hashCode ^
      username.hashCode ^
      permalink.hashCode ^
      permalinkUrl.hashCode ^
      avatarUrl.hashCode ^
      fullName.hashCode ^
      city.hashCode ^
      countryCode.hashCode ^
      description.hashCode ^
      verified.hashCode ^
      followersCount.hashCode ^
      followingsCount.hashCode ^
      trackCount.hashCode ^
      playlistCount.hashCode ^
      publicFavoritesCount.hashCode ^
      plan.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserDto &&
          runtimeType == other.runtimeType &&
          urn == other.urn &&
          username == other.username &&
          permalink == other.permalink &&
          permalinkUrl == other.permalinkUrl &&
          avatarUrl == other.avatarUrl &&
          fullName == other.fullName &&
          city == other.city &&
          countryCode == other.countryCode &&
          description == other.description &&
          verified == other.verified &&
          followersCount == other.followersCount &&
          followingsCount == other.followingsCount &&
          trackCount == other.trackCount &&
          playlistCount == other.playlistCount &&
          publicFavoritesCount == other.publicFavoritesCount &&
          plan == other.plan &&
          createdAt == other.createdAt;
}

class UserPageDto {
  final List<UserDto> items;
  final int page;
  final int pageSize;
  final bool hasMore;

  const UserPageDto({
    required this.items,
    required this.page,
    required this.pageSize,
    required this.hasMore,
  });

  @override
  int get hashCode =>
      items.hashCode ^ page.hashCode ^ pageSize.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          pageSize == other.pageSize &&
          hasMore == other.hasMore;
}

class WaveDto {
  final List<WaveItemDto> items;
  final String? cursor;

  const WaveDto({
    required this.items,
    this.cursor,
  });

  @override
  int get hashCode => items.hashCode ^ cursor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WaveDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          cursor == other.cursor;
}

class WaveItemDto {
  final PlatformInt64 id;
  final double score;

  const WaveItemDto({
    required this.id,
    required this.score,
  });

  @override
  int get hashCode => id.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WaveItemDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          score == other.score;
}
