// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class CheckoutDto {
  final String orderId;
  final String provider;
  final String status;
  final String currency;
  final PlatformInt64 amountRub;
  final PlatformInt64 amountMinor;
  final bool recurring;
  final String? payUrl;
  final List<PayTargetDto> payTargets;
  final String? sbpQr;
  final PlatformInt64 expiresAt;

  const CheckoutDto({
    required this.orderId,
    required this.provider,
    required this.status,
    required this.currency,
    required this.amountRub,
    required this.amountMinor,
    required this.recurring,
    this.payUrl,
    required this.payTargets,
    this.sbpQr,
    required this.expiresAt,
  });

  @override
  int get hashCode =>
      orderId.hashCode ^
      provider.hashCode ^
      status.hashCode ^
      currency.hashCode ^
      amountRub.hashCode ^
      amountMinor.hashCode ^
      recurring.hashCode ^
      payUrl.hashCode ^
      payTargets.hashCode ^
      sbpQr.hashCode ^
      expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CheckoutDto &&
          runtimeType == other.runtimeType &&
          orderId == other.orderId &&
          provider == other.provider &&
          status == other.status &&
          currency == other.currency &&
          amountRub == other.amountRub &&
          amountMinor == other.amountMinor &&
          recurring == other.recurring &&
          payUrl == other.payUrl &&
          payTargets == other.payTargets &&
          sbpQr == other.sbpQr &&
          expiresAt == other.expiresAt;
}

class EntitlementDto {
  final String source;
  final PlatformInt64 startsAt;
  final PlatformInt64 endsAt;
  final bool recurring;
  final bool autoRenew;
  final bool canceled;

  const EntitlementDto({
    required this.source,
    required this.startsAt,
    required this.endsAt,
    required this.recurring,
    required this.autoRenew,
    required this.canceled,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      startsAt.hashCode ^
      endsAt.hashCode ^
      recurring.hashCode ^
      autoRenew.hashCode ^
      canceled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntitlementDto &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          startsAt == other.startsAt &&
          endsAt == other.endsAt &&
          recurring == other.recurring &&
          autoRenew == other.autoRenew &&
          canceled == other.canceled;
}

class OrderDto {
  final String id;
  final String planId;
  final String provider;
  final String? method;
  final String status;
  final String currency;
  final PlatformInt64 amountRub;
  final PlatformInt64? amountMinor;
  final bool recurring;
  final String? payUrl;
  final String? sbpQr;
  final PlatformInt64 createdAt;
  final PlatformInt64? paidAt;
  final PlatformInt64? grantedAt;
  final PlatformInt64? expiresAt;
  final PlatformInt64? premiumUntil;

  const OrderDto({
    required this.id,
    required this.planId,
    required this.provider,
    this.method,
    required this.status,
    required this.currency,
    required this.amountRub,
    this.amountMinor,
    required this.recurring,
    this.payUrl,
    this.sbpQr,
    required this.createdAt,
    this.paidAt,
    this.grantedAt,
    this.expiresAt,
    this.premiumUntil,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      planId.hashCode ^
      provider.hashCode ^
      method.hashCode ^
      status.hashCode ^
      currency.hashCode ^
      amountRub.hashCode ^
      amountMinor.hashCode ^
      recurring.hashCode ^
      payUrl.hashCode ^
      sbpQr.hashCode ^
      createdAt.hashCode ^
      paidAt.hashCode ^
      grantedAt.hashCode ^
      expiresAt.hashCode ^
      premiumUntil.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrderDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          planId == other.planId &&
          provider == other.provider &&
          method == other.method &&
          status == other.status &&
          currency == other.currency &&
          amountRub == other.amountRub &&
          amountMinor == other.amountMinor &&
          recurring == other.recurring &&
          payUrl == other.payUrl &&
          sbpQr == other.sbpQr &&
          createdAt == other.createdAt &&
          paidAt == other.paidAt &&
          grantedAt == other.grantedAt &&
          expiresAt == other.expiresAt &&
          premiumUntil == other.premiumUntil;
}

class PayTargetDto {
  final String kind;
  final String url;

  const PayTargetDto({
    required this.kind,
    required this.url,
  });

  @override
  int get hashCode => kind.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PayTargetDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          url == other.url;
}

class PlanDto {
  final String id;
  final PlatformInt64 months;
  final PlatformInt64 periodDays;
  final PlatformInt64 priceRub;
  final PlatformInt64 savingsPct;
  final PlatformInt64 stars;

  const PlanDto({
    required this.id,
    required this.months,
    required this.periodDays,
    required this.priceRub,
    required this.savingsPct,
    required this.stars,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      months.hashCode ^
      periodDays.hashCode ^
      priceRub.hashCode ^
      savingsPct.hashCode ^
      stars.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlanDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          months == other.months &&
          periodDays == other.periodDays &&
          priceRub == other.priceRub &&
          savingsPct == other.savingsPct &&
          stars == other.stars;
}

class RedeemDto {
  final String? planId;
  final PlatformInt64? periodDays;
  final PlatformInt64? premiumUntil;

  const RedeemDto({
    this.planId,
    this.periodDays,
    this.premiumUntil,
  });

  @override
  int get hashCode =>
      planId.hashCode ^ periodDays.hashCode ^ premiumUntil.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RedeemDto &&
          runtimeType == other.runtimeType &&
          planId == other.planId &&
          periodDays == other.periodDays &&
          premiumUntil == other.premiumUntil;
}

class SubscriptionDto {
  final bool premium;
  final PlatformInt64 premiumUntil;
  final List<EntitlementDto> entitlements;

  const SubscriptionDto({
    required this.premium,
    required this.premiumUntil,
    required this.entitlements,
  });

  @override
  int get hashCode =>
      premium.hashCode ^ premiumUntil.hashCode ^ entitlements.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubscriptionDto &&
          runtimeType == other.runtimeType &&
          premium == other.premium &&
          premiumUntil == other.premiumUntil &&
          entitlements == other.entitlements;
}
