// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'api.dart';
import 'dto.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'dto_social.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class AlbumYearBucketDto {
  final int year;
  final List<AlbumCardDto> items;

  const AlbumYearBucketDto({
    required this.year,
    required this.items,
  });

  @override
  int get hashCode => year.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumYearBucketDto &&
          runtimeType == other.runtimeType &&
          year == other.year &&
          items == other.items;
}

class ArtistStarDto {
  final bool premium;
  final String? auraId;
  final String? customHex;
  final String? sourceScUserId;

  const ArtistStarDto({
    required this.premium,
    this.auraId,
    this.customHex,
    this.sourceScUserId,
  });

  @override
  int get hashCode =>
      premium.hashCode ^
      auraId.hashCode ^
      customHex.hashCode ^
      sourceScUserId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtistStarDto &&
          runtimeType == other.runtimeType &&
          premium == other.premium &&
          auraId == other.auraId &&
          customHex == other.customHex &&
          sourceScUserId == other.sourceScUserId;
}

class AuraDto {
  final String? auraId;
  final String? customHex;

  const AuraDto({
    this.auraId,
    this.customHex,
  });

  @override
  int get hashCode => auraId.hashCode ^ customHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuraDto &&
          runtimeType == other.runtimeType &&
          auraId == other.auraId &&
          customHex == other.customHex;
}

/// Запись оффлайн-кэша (один m4a на диске).
class CacheEntryDto {
  final String urn;
  final PlatformInt64 scId;
  final PlatformInt64 bytes;

  const CacheEntryDto({
    required this.urn,
    required this.scId,
    required this.bytes,
  });

  @override
  int get hashCode => urn.hashCode ^ scId.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CacheEntryDto &&
          runtimeType == other.runtimeType &&
          urn == other.urn &&
          scId == other.scId &&
          bytes == other.bytes;
}

/// Курсорная страница каталога альбомов (`/discover/albums`).
class DiscoverAlbumsPageDto {
  final List<AlbumCardDto> items;
  final String? nextCursor;

  const DiscoverAlbumsPageDto({
    required this.items,
    this.nextCursor,
  });

  @override
  int get hashCode => items.hashCode ^ nextCursor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoverAlbumsPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          nextCursor == other.nextCursor;
}

/// Курсорная страница каталога артистов (`/discover/artists`).
class DiscoverArtistsPageDto {
  final List<ArtistCardDto> items;
  final String? nextCursor;

  const DiscoverArtistsPageDto({
    required this.items,
    this.nextCursor,
  });

  @override
  int get hashCode => items.hashCode ^ nextCursor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoverArtistsPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          nextCursor == other.nextCursor;
}

/// Хит поиска по лирике: трек + совпавшая строка текста (для карточки-цитаты).
class LyricHitDto {
  final TrackDto track;
  final String? matchedLine;

  const LyricHitDto({
    required this.track,
    this.matchedLine,
  });

  @override
  int get hashCode => track.hashCode ^ matchedLine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricHitDto &&
          runtimeType == other.runtimeType &&
          track == other.track &&
          matchedLine == other.matchedLine;
}

/// Страница хитов поиска по лирике.
class LyricHitPageDto {
  final List<LyricHitDto> items;
  final int page;
  final int pageSize;
  final bool hasMore;

  const LyricHitPageDto({
    required this.items,
    required this.page,
    required this.pageSize,
    required this.hasMore,
  });

  @override
  int get hashCode =>
      items.hashCode ^ page.hashCode ^ pageSize.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricHitPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          pageSize == other.pageSize &&
          hasMore == other.hasMore;
}

/// Лента «В центре внимания» — курируемые карточки без пагинации.
class SpotlightFeedDto {
  final List<SpotlightItemDto> items;

  const SpotlightFeedDto({
    required this.items,
  });

  @override
  int get hashCode => items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpotlightFeedDto &&
          runtimeType == other.runtimeType &&
          items == other.items;
}

@freezed
sealed class SpotlightItemDto with _$SpotlightItemDto {
  const SpotlightItemDto._();

  const factory SpotlightItemDto.artist(
    ArtistCardDto field0,
  ) = SpotlightItemDto_Artist;
  const factory SpotlightItemDto.album(
    AlbumCardDto field0,
  ) = SpotlightItemDto_Album;
}

/// Результат vibe-поиска: треки + флаг «вектор кодируется» (плашка «Ловим вайб»).
class VibePageDto {
  final List<TrackDto> items;
  final bool preparing;

  const VibePageDto({
    required this.items,
    required this.preparing,
  });

  @override
  int get hashCode => items.hashCode ^ preparing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VibePageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          preparing == other.preparing;
}

/// Один результат поиска обоев.
class WallpaperHitDto {
  final String id;
  final String thumb;
  final String full;
  final String resolution;

  const WallpaperHitDto({
    required this.id,
    required this.thumb,
    required this.full,
    required this.resolution,
  });

  @override
  int get hashCode =>
      id.hashCode ^ thumb.hashCode ^ full.hashCode ^ resolution.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WallpaperHitDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          thumb == other.thumb &&
          full == other.full &&
          resolution == other.resolution;
}

/// Страница обоев + курсор следующей (null — конец).
class WallpaperPageDto {
  final List<WallpaperHitDto> items;
  final String? cursor;

  const WallpaperPageDto({
    required this.items,
    this.cursor,
  });

  @override
  int get hashCode => items.hashCode ^ cursor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WallpaperPageDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          cursor == other.cursor;
}

/// Параметры поиска обоев (вход FRB). `source`: wallhaven|pinterest|konachan|
/// safebooru. `cursor` — непрозрачный токен следующей страницы из [`WallpaperPageDto`].
class WallpaperQueryDto {
  final String source;
  final String query;
  final String? category;
  final String? color;
  final String? cursor;
  final bool adult;
  final String? apiKey;

  const WallpaperQueryDto({
    required this.source,
    required this.query,
    this.category,
    this.color,
    this.cursor,
    required this.adult,
    this.apiKey,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      query.hashCode ^
      category.hashCode ^
      color.hashCode ^
      cursor.hashCode ^
      adult.hashCode ^
      apiKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WallpaperQueryDto &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          query == other.query &&
          category == other.category &&
          color == other.color &&
          cursor == other.cursor &&
          adult == other.adult &&
          apiKey == other.apiKey;
}

class WebProfileDto {
  final String? network;
  final String? title;
  final String url;
  final String? username;

  const WebProfileDto({
    this.network,
    this.title,
    required this.url,
    this.username,
  });

  @override
  int get hashCode =>
      network.hashCode ^ title.hashCode ^ url.hashCode ^ username.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebProfileDto &&
          runtimeType == other.runtimeType &&
          network == other.network &&
          title == other.title &&
          url == other.url &&
          username == other.username;
}
