// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'data.dart';
import 'data_pay.dart';
import 'data_social.dart';
import 'dto.dart';
import 'dto_pay.dart';
import 'dto_social.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<DownloadProgressDto>
      dco_decode_StreamSink_download_progress_dto_Sse(dynamic raw);

  @protected
  RustStreamSink<double> dco_decode_StreamSink_f_64_Sse(dynamic raw);

  @protected
  RustStreamSink<HostStatusDto> dco_decode_StreamSink_host_status_dto_Sse(
      dynamic raw);

  @protected
  RustStreamSink<LikesProgressDto> dco_decode_StreamSink_likes_progress_dto_Sse(
      dynamic raw);

  @protected
  RustStreamSink<Float32List> dco_decode_StreamSink_list_prim_f_32_strict_Sse(
      dynamic raw);

  @protected
  RustStreamSink<PlaybackEventDto> dco_decode_StreamSink_playback_event_dto_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AlbumArtistDto dco_decode_album_artist_dto(dynamic raw);

  @protected
  AlbumCardDto dco_decode_album_card_dto(dynamic raw);

  @protected
  AlbumCardPageDto dco_decode_album_card_page_dto(dynamic raw);

  @protected
  AlbumDetailDto dco_decode_album_detail_dto(dynamic raw);

  @protected
  AlbumRefDto dco_decode_album_ref_dto(dynamic raw);

  @protected
  AlbumYearBucketDto dco_decode_album_year_bucket_dto(dynamic raw);

  @protected
  ArtistCardDto dco_decode_artist_card_dto(dynamic raw);

  @protected
  ArtistCardPageDto dco_decode_artist_card_page_dto(dynamic raw);

  @protected
  ArtistDetailDto dco_decode_artist_detail_dto(dynamic raw);

  @protected
  ArtistStarDto dco_decode_artist_star_dto(dynamic raw);

  @protected
  AudioDeviceDto dco_decode_audio_device_dto(dynamic raw);

  @protected
  AuraDto dco_decode_aura_dto(dynamic raw);

  @protected
  AuthStatusDto dco_decode_auth_status_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AlbumCardDto dco_decode_box_autoadd_album_card_dto(dynamic raw);

  @protected
  ArtistCardDto dco_decode_box_autoadd_artist_card_dto(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  LyricsDto dco_decode_box_autoadd_lyrics_dto(dynamic raw);

  @protected
  OrderDto dco_decode_box_autoadd_order_dto(dynamic raw);

  @protected
  PlaylistSummaryDto dco_decode_box_autoadd_playlist_summary_dto(dynamic raw);

  @protected
  TrackAlbumDto dco_decode_box_autoadd_track_album_dto(dynamic raw);

  @protected
  TrackDto dco_decode_box_autoadd_track_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  UserDto dco_decode_box_autoadd_user_dto(dynamic raw);

  @protected
  WallpaperQueryDto dco_decode_box_autoadd_wallpaper_query_dto(dynamic raw);

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw);

  @protected
  CacheEntryDto dco_decode_cache_entry_dto(dynamic raw);

  @protected
  CheckoutDto dco_decode_checkout_dto(dynamic raw);

  @protected
  ClusterDto dco_decode_cluster_dto(dynamic raw);

  @protected
  ClusterNeighborDto dco_decode_cluster_neighbor_dto(dynamic raw);

  @protected
  CommentDto dco_decode_comment_dto(dynamic raw);

  @protected
  CommentPageDto dco_decode_comment_page_dto(dynamic raw);

  @protected
  DiscoverAlbumsPageDto dco_decode_discover_albums_page_dto(dynamic raw);

  @protected
  DiscoverArtistsPageDto dco_decode_discover_artists_page_dto(dynamic raw);

  @protected
  DiscoverSummaryDto dco_decode_discover_summary_dto(dynamic raw);

  @protected
  DownloadProgressDto dco_decode_download_progress_dto(dynamic raw);

  @protected
  EntitlementDto dco_decode_entitlement_dto(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FeaturedDto dco_decode_featured_dto(dynamic raw);

  @protected
  HistoryEntryDto dco_decode_history_entry_dto(dynamic raw);

  @protected
  HistoryPageDto dco_decode_history_page_dto(dynamic raw);

  @protected
  HostStatusDto dco_decode_host_status_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LikesProgressDto dco_decode_likes_progress_dto(dynamic raw);

  @protected
  LinkClaimDto dco_decode_link_claim_dto(dynamic raw);

  @protected
  LinkCreateDto dco_decode_link_create_dto(dynamic raw);

  @protected
  LinkStatusDto dco_decode_link_status_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AlbumArtistDto> dco_decode_list_album_artist_dto(dynamic raw);

  @protected
  List<AlbumCardDto> dco_decode_list_album_card_dto(dynamic raw);

  @protected
  List<AlbumRefDto> dco_decode_list_album_ref_dto(dynamic raw);

  @protected
  List<AlbumYearBucketDto> dco_decode_list_album_year_bucket_dto(dynamic raw);

  @protected
  List<ArtistCardDto> dco_decode_list_artist_card_dto(dynamic raw);

  @protected
  List<AudioDeviceDto> dco_decode_list_audio_device_dto(dynamic raw);

  @protected
  List<CacheEntryDto> dco_decode_list_cache_entry_dto(dynamic raw);

  @protected
  List<ClusterDto> dco_decode_list_cluster_dto(dynamic raw);

  @protected
  List<ClusterNeighborDto> dco_decode_list_cluster_neighbor_dto(dynamic raw);

  @protected
  List<CommentDto> dco_decode_list_comment_dto(dynamic raw);

  @protected
  List<EntitlementDto> dco_decode_list_entitlement_dto(dynamic raw);

  @protected
  List<HistoryEntryDto> dco_decode_list_history_entry_dto(dynamic raw);

  @protected
  List<LyricHitDto> dco_decode_list_lyric_hit_dto(dynamic raw);

  @protected
  List<LyricLineDto> dco_decode_list_lyric_line_dto(dynamic raw);

  @protected
  List<OrderDto> dco_decode_list_order_dto(dynamic raw);

  @protected
  List<PayTargetDto> dco_decode_list_pay_target_dto(dynamic raw);

  @protected
  List<PlanDto> dco_decode_list_plan_dto(dynamic raw);

  @protected
  List<PlaylistSummaryDto> dco_decode_list_playlist_summary_dto(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_64_loose(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RelatedArtistDto> dco_decode_list_related_artist_dto(dynamic raw);

  @protected
  List<ScAccountDto> dco_decode_list_sc_account_dto(dynamic raw);

  @protected
  List<SocialDto> dco_decode_list_social_dto(dynamic raw);

  @protected
  List<SpotlightItemDto> dco_decode_list_spotlight_item_dto(dynamic raw);

  @protected
  List<TagDto> dco_decode_list_tag_dto(dynamic raw);

  @protected
  List<TrackDto> dco_decode_list_track_dto(dynamic raw);

  @protected
  List<TrackParticipantDto> dco_decode_list_track_participant_dto(dynamic raw);

  @protected
  List<UserDto> dco_decode_list_user_dto(dynamic raw);

  @protected
  List<WallpaperHitDto> dco_decode_list_wallpaper_hit_dto(dynamic raw);

  @protected
  List<WaveItemDto> dco_decode_list_wave_item_dto(dynamic raw);

  @protected
  List<WebProfileDto> dco_decode_list_web_profile_dto(dynamic raw);

  @protected
  LoginStartDto dco_decode_login_start_dto(dynamic raw);

  @protected
  LoginStatusDto dco_decode_login_status_dto(dynamic raw);

  @protected
  LyricHitDto dco_decode_lyric_hit_dto(dynamic raw);

  @protected
  LyricHitPageDto dco_decode_lyric_hit_page_dto(dynamic raw);

  @protected
  LyricLineDto dco_decode_lyric_line_dto(dynamic raw);

  @protected
  LyricsDto dco_decode_lyrics_dto(dynamic raw);

  @protected
  MeDto dco_decode_me_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  LyricsDto? dco_decode_opt_box_autoadd_lyrics_dto(dynamic raw);

  @protected
  OrderDto? dco_decode_opt_box_autoadd_order_dto(dynamic raw);

  @protected
  PlaylistSummaryDto? dco_decode_opt_box_autoadd_playlist_summary_dto(
      dynamic raw);

  @protected
  TrackAlbumDto? dco_decode_opt_box_autoadd_track_album_dto(dynamic raw);

  @protected
  TrackDto? dco_decode_opt_box_autoadd_track_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  UserDto? dco_decode_opt_box_autoadd_user_dto(dynamic raw);

  @protected
  OrderDto dco_decode_order_dto(dynamic raw);

  @protected
  PayTargetDto dco_decode_pay_target_dto(dynamic raw);

  @protected
  PlanDto dco_decode_plan_dto(dynamic raw);

  @protected
  PlaybackEventDto dco_decode_playback_event_dto(dynamic raw);

  @protected
  PlaylistDetailDto dco_decode_playlist_detail_dto(dynamic raw);

  @protected
  PlaylistSummaryDto dco_decode_playlist_summary_dto(dynamic raw);

  @protected
  PlaylistSummaryPageDto dco_decode_playlist_summary_page_dto(dynamic raw);

  @protected
  RedeemDto dco_decode_redeem_dto(dynamic raw);

  @protected
  RelatedArtistDto dco_decode_related_artist_dto(dynamic raw);

  @protected
  ScAccountDto dco_decode_sc_account_dto(dynamic raw);

  @protected
  SocialDto dco_decode_social_dto(dynamic raw);

  @protected
  SpotlightFeedDto dco_decode_spotlight_feed_dto(dynamic raw);

  @protected
  SpotlightItemDto dco_decode_spotlight_item_dto(dynamic raw);

  @protected
  SubscriptionDto dco_decode_subscription_dto(dynamic raw);

  @protected
  TagDto dco_decode_tag_dto(dynamic raw);

  @protected
  TrackAlbumDto dco_decode_track_album_dto(dynamic raw);

  @protected
  TrackDto dco_decode_track_dto(dynamic raw);

  @protected
  TrackPageDto dco_decode_track_page_dto(dynamic raw);

  @protected
  TrackParticipantDto dco_decode_track_participant_dto(dynamic raw);

  @protected
  TrackStreamsDto dco_decode_track_streams_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserDto dco_decode_user_dto(dynamic raw);

  @protected
  UserPageDto dco_decode_user_page_dto(dynamic raw);

  @protected
  VibePageDto dco_decode_vibe_page_dto(dynamic raw);

  @protected
  WallpaperHitDto dco_decode_wallpaper_hit_dto(dynamic raw);

  @protected
  WallpaperPageDto dco_decode_wallpaper_page_dto(dynamic raw);

  @protected
  WallpaperQueryDto dco_decode_wallpaper_query_dto(dynamic raw);

  @protected
  WaveDto dco_decode_wave_dto(dynamic raw);

  @protected
  WaveItemDto dco_decode_wave_item_dto(dynamic raw);

  @protected
  WebProfileDto dco_decode_web_profile_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<DownloadProgressDto>
      sse_decode_StreamSink_download_progress_dto_Sse(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<double> sse_decode_StreamSink_f_64_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<HostStatusDto> sse_decode_StreamSink_host_status_dto_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<LikesProgressDto> sse_decode_StreamSink_likes_progress_dto_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<Float32List> sse_decode_StreamSink_list_prim_f_32_strict_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<PlaybackEventDto> sse_decode_StreamSink_playback_event_dto_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AlbumArtistDto sse_decode_album_artist_dto(SseDeserializer deserializer);

  @protected
  AlbumCardDto sse_decode_album_card_dto(SseDeserializer deserializer);

  @protected
  AlbumCardPageDto sse_decode_album_card_page_dto(SseDeserializer deserializer);

  @protected
  AlbumDetailDto sse_decode_album_detail_dto(SseDeserializer deserializer);

  @protected
  AlbumRefDto sse_decode_album_ref_dto(SseDeserializer deserializer);

  @protected
  AlbumYearBucketDto sse_decode_album_year_bucket_dto(
      SseDeserializer deserializer);

  @protected
  ArtistCardDto sse_decode_artist_card_dto(SseDeserializer deserializer);

  @protected
  ArtistCardPageDto sse_decode_artist_card_page_dto(
      SseDeserializer deserializer);

  @protected
  ArtistDetailDto sse_decode_artist_detail_dto(SseDeserializer deserializer);

  @protected
  ArtistStarDto sse_decode_artist_star_dto(SseDeserializer deserializer);

  @protected
  AudioDeviceDto sse_decode_audio_device_dto(SseDeserializer deserializer);

  @protected
  AuraDto sse_decode_aura_dto(SseDeserializer deserializer);

  @protected
  AuthStatusDto sse_decode_auth_status_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AlbumCardDto sse_decode_box_autoadd_album_card_dto(
      SseDeserializer deserializer);

  @protected
  ArtistCardDto sse_decode_box_autoadd_artist_card_dto(
      SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LyricsDto sse_decode_box_autoadd_lyrics_dto(SseDeserializer deserializer);

  @protected
  OrderDto sse_decode_box_autoadd_order_dto(SseDeserializer deserializer);

  @protected
  PlaylistSummaryDto sse_decode_box_autoadd_playlist_summary_dto(
      SseDeserializer deserializer);

  @protected
  TrackAlbumDto sse_decode_box_autoadd_track_album_dto(
      SseDeserializer deserializer);

  @protected
  TrackDto sse_decode_box_autoadd_track_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  UserDto sse_decode_box_autoadd_user_dto(SseDeserializer deserializer);

  @protected
  WallpaperQueryDto sse_decode_box_autoadd_wallpaper_query_dto(
      SseDeserializer deserializer);

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer);

  @protected
  CacheEntryDto sse_decode_cache_entry_dto(SseDeserializer deserializer);

  @protected
  CheckoutDto sse_decode_checkout_dto(SseDeserializer deserializer);

  @protected
  ClusterDto sse_decode_cluster_dto(SseDeserializer deserializer);

  @protected
  ClusterNeighborDto sse_decode_cluster_neighbor_dto(
      SseDeserializer deserializer);

  @protected
  CommentDto sse_decode_comment_dto(SseDeserializer deserializer);

  @protected
  CommentPageDto sse_decode_comment_page_dto(SseDeserializer deserializer);

  @protected
  DiscoverAlbumsPageDto sse_decode_discover_albums_page_dto(
      SseDeserializer deserializer);

  @protected
  DiscoverArtistsPageDto sse_decode_discover_artists_page_dto(
      SseDeserializer deserializer);

  @protected
  DiscoverSummaryDto sse_decode_discover_summary_dto(
      SseDeserializer deserializer);

  @protected
  DownloadProgressDto sse_decode_download_progress_dto(
      SseDeserializer deserializer);

  @protected
  EntitlementDto sse_decode_entitlement_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FeaturedDto sse_decode_featured_dto(SseDeserializer deserializer);

  @protected
  HistoryEntryDto sse_decode_history_entry_dto(SseDeserializer deserializer);

  @protected
  HistoryPageDto sse_decode_history_page_dto(SseDeserializer deserializer);

  @protected
  HostStatusDto sse_decode_host_status_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LikesProgressDto sse_decode_likes_progress_dto(SseDeserializer deserializer);

  @protected
  LinkClaimDto sse_decode_link_claim_dto(SseDeserializer deserializer);

  @protected
  LinkCreateDto sse_decode_link_create_dto(SseDeserializer deserializer);

  @protected
  LinkStatusDto sse_decode_link_status_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AlbumArtistDto> sse_decode_list_album_artist_dto(
      SseDeserializer deserializer);

  @protected
  List<AlbumCardDto> sse_decode_list_album_card_dto(
      SseDeserializer deserializer);

  @protected
  List<AlbumRefDto> sse_decode_list_album_ref_dto(SseDeserializer deserializer);

  @protected
  List<AlbumYearBucketDto> sse_decode_list_album_year_bucket_dto(
      SseDeserializer deserializer);

  @protected
  List<ArtistCardDto> sse_decode_list_artist_card_dto(
      SseDeserializer deserializer);

  @protected
  List<AudioDeviceDto> sse_decode_list_audio_device_dto(
      SseDeserializer deserializer);

  @protected
  List<CacheEntryDto> sse_decode_list_cache_entry_dto(
      SseDeserializer deserializer);

  @protected
  List<ClusterDto> sse_decode_list_cluster_dto(SseDeserializer deserializer);

  @protected
  List<ClusterNeighborDto> sse_decode_list_cluster_neighbor_dto(
      SseDeserializer deserializer);

  @protected
  List<CommentDto> sse_decode_list_comment_dto(SseDeserializer deserializer);

  @protected
  List<EntitlementDto> sse_decode_list_entitlement_dto(
      SseDeserializer deserializer);

  @protected
  List<HistoryEntryDto> sse_decode_list_history_entry_dto(
      SseDeserializer deserializer);

  @protected
  List<LyricHitDto> sse_decode_list_lyric_hit_dto(SseDeserializer deserializer);

  @protected
  List<LyricLineDto> sse_decode_list_lyric_line_dto(
      SseDeserializer deserializer);

  @protected
  List<OrderDto> sse_decode_list_order_dto(SseDeserializer deserializer);

  @protected
  List<PayTargetDto> sse_decode_list_pay_target_dto(
      SseDeserializer deserializer);

  @protected
  List<PlanDto> sse_decode_list_plan_dto(SseDeserializer deserializer);

  @protected
  List<PlaylistSummaryDto> sse_decode_list_playlist_summary_dto(
      SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  List<double> sse_decode_list_prim_f_64_loose(SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RelatedArtistDto> sse_decode_list_related_artist_dto(
      SseDeserializer deserializer);

  @protected
  List<ScAccountDto> sse_decode_list_sc_account_dto(
      SseDeserializer deserializer);

  @protected
  List<SocialDto> sse_decode_list_social_dto(SseDeserializer deserializer);

  @protected
  List<SpotlightItemDto> sse_decode_list_spotlight_item_dto(
      SseDeserializer deserializer);

  @protected
  List<TagDto> sse_decode_list_tag_dto(SseDeserializer deserializer);

  @protected
  List<TrackDto> sse_decode_list_track_dto(SseDeserializer deserializer);

  @protected
  List<TrackParticipantDto> sse_decode_list_track_participant_dto(
      SseDeserializer deserializer);

  @protected
  List<UserDto> sse_decode_list_user_dto(SseDeserializer deserializer);

  @protected
  List<WallpaperHitDto> sse_decode_list_wallpaper_hit_dto(
      SseDeserializer deserializer);

  @protected
  List<WaveItemDto> sse_decode_list_wave_item_dto(SseDeserializer deserializer);

  @protected
  List<WebProfileDto> sse_decode_list_web_profile_dto(
      SseDeserializer deserializer);

  @protected
  LoginStartDto sse_decode_login_start_dto(SseDeserializer deserializer);

  @protected
  LoginStatusDto sse_decode_login_status_dto(SseDeserializer deserializer);

  @protected
  LyricHitDto sse_decode_lyric_hit_dto(SseDeserializer deserializer);

  @protected
  LyricHitPageDto sse_decode_lyric_hit_page_dto(SseDeserializer deserializer);

  @protected
  LyricLineDto sse_decode_lyric_line_dto(SseDeserializer deserializer);

  @protected
  LyricsDto sse_decode_lyrics_dto(SseDeserializer deserializer);

  @protected
  MeDto sse_decode_me_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LyricsDto? sse_decode_opt_box_autoadd_lyrics_dto(
      SseDeserializer deserializer);

  @protected
  OrderDto? sse_decode_opt_box_autoadd_order_dto(SseDeserializer deserializer);

  @protected
  PlaylistSummaryDto? sse_decode_opt_box_autoadd_playlist_summary_dto(
      SseDeserializer deserializer);

  @protected
  TrackAlbumDto? sse_decode_opt_box_autoadd_track_album_dto(
      SseDeserializer deserializer);

  @protected
  TrackDto? sse_decode_opt_box_autoadd_track_dto(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  UserDto? sse_decode_opt_box_autoadd_user_dto(SseDeserializer deserializer);

  @protected
  OrderDto sse_decode_order_dto(SseDeserializer deserializer);

  @protected
  PayTargetDto sse_decode_pay_target_dto(SseDeserializer deserializer);

  @protected
  PlanDto sse_decode_plan_dto(SseDeserializer deserializer);

  @protected
  PlaybackEventDto sse_decode_playback_event_dto(SseDeserializer deserializer);

  @protected
  PlaylistDetailDto sse_decode_playlist_detail_dto(
      SseDeserializer deserializer);

  @protected
  PlaylistSummaryDto sse_decode_playlist_summary_dto(
      SseDeserializer deserializer);

  @protected
  PlaylistSummaryPageDto sse_decode_playlist_summary_page_dto(
      SseDeserializer deserializer);

  @protected
  RedeemDto sse_decode_redeem_dto(SseDeserializer deserializer);

  @protected
  RelatedArtistDto sse_decode_related_artist_dto(SseDeserializer deserializer);

  @protected
  ScAccountDto sse_decode_sc_account_dto(SseDeserializer deserializer);

  @protected
  SocialDto sse_decode_social_dto(SseDeserializer deserializer);

  @protected
  SpotlightFeedDto sse_decode_spotlight_feed_dto(SseDeserializer deserializer);

  @protected
  SpotlightItemDto sse_decode_spotlight_item_dto(SseDeserializer deserializer);

  @protected
  SubscriptionDto sse_decode_subscription_dto(SseDeserializer deserializer);

  @protected
  TagDto sse_decode_tag_dto(SseDeserializer deserializer);

  @protected
  TrackAlbumDto sse_decode_track_album_dto(SseDeserializer deserializer);

  @protected
  TrackDto sse_decode_track_dto(SseDeserializer deserializer);

  @protected
  TrackPageDto sse_decode_track_page_dto(SseDeserializer deserializer);

  @protected
  TrackParticipantDto sse_decode_track_participant_dto(
      SseDeserializer deserializer);

  @protected
  TrackStreamsDto sse_decode_track_streams_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserDto sse_decode_user_dto(SseDeserializer deserializer);

  @protected
  UserPageDto sse_decode_user_page_dto(SseDeserializer deserializer);

  @protected
  VibePageDto sse_decode_vibe_page_dto(SseDeserializer deserializer);

  @protected
  WallpaperHitDto sse_decode_wallpaper_hit_dto(SseDeserializer deserializer);

  @protected
  WallpaperPageDto sse_decode_wallpaper_page_dto(SseDeserializer deserializer);

  @protected
  WallpaperQueryDto sse_decode_wallpaper_query_dto(
      SseDeserializer deserializer);

  @protected
  WaveDto sse_decode_wave_dto(SseDeserializer deserializer);

  @protected
  WaveItemDto sse_decode_wave_item_dto(SseDeserializer deserializer);

  @protected
  WebProfileDto sse_decode_web_profile_dto(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_download_progress_dto_Sse(
      RustStreamSink<DownloadProgressDto> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_f_64_Sse(
      RustStreamSink<double> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_host_status_dto_Sse(
      RustStreamSink<HostStatusDto> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_likes_progress_dto_Sse(
      RustStreamSink<LikesProgressDto> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_list_prim_f_32_strict_Sse(
      RustStreamSink<Float32List> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_playback_event_dto_Sse(
      RustStreamSink<PlaybackEventDto> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_album_artist_dto(
      AlbumArtistDto self, SseSerializer serializer);

  @protected
  void sse_encode_album_card_dto(AlbumCardDto self, SseSerializer serializer);

  @protected
  void sse_encode_album_card_page_dto(
      AlbumCardPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_album_detail_dto(
      AlbumDetailDto self, SseSerializer serializer);

  @protected
  void sse_encode_album_ref_dto(AlbumRefDto self, SseSerializer serializer);

  @protected
  void sse_encode_album_year_bucket_dto(
      AlbumYearBucketDto self, SseSerializer serializer);

  @protected
  void sse_encode_artist_card_dto(ArtistCardDto self, SseSerializer serializer);

  @protected
  void sse_encode_artist_card_page_dto(
      ArtistCardPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_artist_detail_dto(
      ArtistDetailDto self, SseSerializer serializer);

  @protected
  void sse_encode_artist_star_dto(ArtistStarDto self, SseSerializer serializer);

  @protected
  void sse_encode_audio_device_dto(
      AudioDeviceDto self, SseSerializer serializer);

  @protected
  void sse_encode_aura_dto(AuraDto self, SseSerializer serializer);

  @protected
  void sse_encode_auth_status_dto(AuthStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_album_card_dto(
      AlbumCardDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_artist_card_dto(
      ArtistCardDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_lyrics_dto(
      LyricsDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_order_dto(
      OrderDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_playlist_summary_dto(
      PlaylistSummaryDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_track_album_dto(
      TrackAlbumDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_track_dto(
      TrackDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_user_dto(UserDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_wallpaper_query_dto(
      WallpaperQueryDto self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer);

  @protected
  void sse_encode_cache_entry_dto(CacheEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_checkout_dto(CheckoutDto self, SseSerializer serializer);

  @protected
  void sse_encode_cluster_dto(ClusterDto self, SseSerializer serializer);

  @protected
  void sse_encode_cluster_neighbor_dto(
      ClusterNeighborDto self, SseSerializer serializer);

  @protected
  void sse_encode_comment_dto(CommentDto self, SseSerializer serializer);

  @protected
  void sse_encode_comment_page_dto(
      CommentPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_discover_albums_page_dto(
      DiscoverAlbumsPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_discover_artists_page_dto(
      DiscoverArtistsPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_discover_summary_dto(
      DiscoverSummaryDto self, SseSerializer serializer);

  @protected
  void sse_encode_download_progress_dto(
      DownloadProgressDto self, SseSerializer serializer);

  @protected
  void sse_encode_entitlement_dto(
      EntitlementDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_featured_dto(FeaturedDto self, SseSerializer serializer);

  @protected
  void sse_encode_history_entry_dto(
      HistoryEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_history_page_dto(
      HistoryPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_host_status_dto(HostStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_likes_progress_dto(
      LikesProgressDto self, SseSerializer serializer);

  @protected
  void sse_encode_link_claim_dto(LinkClaimDto self, SseSerializer serializer);

  @protected
  void sse_encode_link_create_dto(LinkCreateDto self, SseSerializer serializer);

  @protected
  void sse_encode_link_status_dto(LinkStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_album_artist_dto(
      List<AlbumArtistDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_album_card_dto(
      List<AlbumCardDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_album_ref_dto(
      List<AlbumRefDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_album_year_bucket_dto(
      List<AlbumYearBucketDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_artist_card_dto(
      List<ArtistCardDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_audio_device_dto(
      List<AudioDeviceDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cache_entry_dto(
      List<CacheEntryDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cluster_dto(
      List<ClusterDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cluster_neighbor_dto(
      List<ClusterNeighborDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_comment_dto(
      List<CommentDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_entitlement_dto(
      List<EntitlementDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_history_entry_dto(
      List<HistoryEntryDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_lyric_hit_dto(
      List<LyricHitDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_lyric_line_dto(
      List<LyricLineDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_order_dto(List<OrderDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_pay_target_dto(
      List<PayTargetDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_plan_dto(List<PlanDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_playlist_summary_dto(
      List<PlaylistSummaryDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_strict(
      Float32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_64_loose(
      List<double> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_64_strict(
      Float64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_related_artist_dto(
      List<RelatedArtistDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_sc_account_dto(
      List<ScAccountDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_social_dto(
      List<SocialDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_spotlight_item_dto(
      List<SpotlightItemDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tag_dto(List<TagDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_track_dto(List<TrackDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_track_participant_dto(
      List<TrackParticipantDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_user_dto(List<UserDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_wallpaper_hit_dto(
      List<WallpaperHitDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_wave_item_dto(
      List<WaveItemDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_web_profile_dto(
      List<WebProfileDto> self, SseSerializer serializer);

  @protected
  void sse_encode_login_start_dto(LoginStartDto self, SseSerializer serializer);

  @protected
  void sse_encode_login_status_dto(
      LoginStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_lyric_hit_dto(LyricHitDto self, SseSerializer serializer);

  @protected
  void sse_encode_lyric_hit_page_dto(
      LyricHitPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_lyric_line_dto(LyricLineDto self, SseSerializer serializer);

  @protected
  void sse_encode_lyrics_dto(LyricsDto self, SseSerializer serializer);

  @protected
  void sse_encode_me_dto(MeDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_lyrics_dto(
      LyricsDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_order_dto(
      OrderDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_playlist_summary_dto(
      PlaylistSummaryDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_track_album_dto(
      TrackAlbumDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_track_dto(
      TrackDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_user_dto(
      UserDto? self, SseSerializer serializer);

  @protected
  void sse_encode_order_dto(OrderDto self, SseSerializer serializer);

  @protected
  void sse_encode_pay_target_dto(PayTargetDto self, SseSerializer serializer);

  @protected
  void sse_encode_plan_dto(PlanDto self, SseSerializer serializer);

  @protected
  void sse_encode_playback_event_dto(
      PlaybackEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_playlist_detail_dto(
      PlaylistDetailDto self, SseSerializer serializer);

  @protected
  void sse_encode_playlist_summary_dto(
      PlaylistSummaryDto self, SseSerializer serializer);

  @protected
  void sse_encode_playlist_summary_page_dto(
      PlaylistSummaryPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_redeem_dto(RedeemDto self, SseSerializer serializer);

  @protected
  void sse_encode_related_artist_dto(
      RelatedArtistDto self, SseSerializer serializer);

  @protected
  void sse_encode_sc_account_dto(ScAccountDto self, SseSerializer serializer);

  @protected
  void sse_encode_social_dto(SocialDto self, SseSerializer serializer);

  @protected
  void sse_encode_spotlight_feed_dto(
      SpotlightFeedDto self, SseSerializer serializer);

  @protected
  void sse_encode_spotlight_item_dto(
      SpotlightItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_subscription_dto(
      SubscriptionDto self, SseSerializer serializer);

  @protected
  void sse_encode_tag_dto(TagDto self, SseSerializer serializer);

  @protected
  void sse_encode_track_album_dto(TrackAlbumDto self, SseSerializer serializer);

  @protected
  void sse_encode_track_dto(TrackDto self, SseSerializer serializer);

  @protected
  void sse_encode_track_page_dto(TrackPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_track_participant_dto(
      TrackParticipantDto self, SseSerializer serializer);

  @protected
  void sse_encode_track_streams_dto(
      TrackStreamsDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_dto(UserDto self, SseSerializer serializer);

  @protected
  void sse_encode_user_page_dto(UserPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_vibe_page_dto(VibePageDto self, SseSerializer serializer);

  @protected
  void sse_encode_wallpaper_hit_dto(
      WallpaperHitDto self, SseSerializer serializer);

  @protected
  void sse_encode_wallpaper_page_dto(
      WallpaperPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_wallpaper_query_dto(
      WallpaperQueryDto self, SseSerializer serializer);

  @protected
  void sse_encode_wave_dto(WaveDto self, SseSerializer serializer);

  @protected
  void sse_encode_wave_item_dto(WaveItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_web_profile_dto(WebProfileDto self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
